name: Frontend & Backend CI/CD

on:
  push:
    tags:
      - "v*"
      - "dev-*"
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name (e.g. v2.5.9 or dev-2.5.9)"
        required: true
        type: string

jobs:
  frontend-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: Frontend/package-lock.json

      - name: Install Frontend Dependencies
        working-directory: ./Frontend
        run: npm ci

      - name: Frontend Linting
        working-directory: ./Frontend
        run: npm run lint

      - name: Frontend Tests
        working-directory: ./Frontend
        run: npm run test

      - name: Frontend Build
        working-directory: ./Frontend
        env:
          NEXT_SERVER_ACTIONS_ENCRYPTION_KEY: ${{ secrets.NEXT_SERVER_ACTIONS_ENCRYPTION_KEY }}
        run: NODE_ENV=production npm run build

  backend-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: Backend/package-lock.json

      - name: Install Backend Dependencies
        working-directory: ./Backend
        run: npm ci

      - name: Backend Linting
        working-directory: ./Backend
        run: npm run lint

      - name: Backend Tests
        working-directory: ./Backend
        run: npm run test

      - name: Backend Build
        working-directory: ./Backend
        run: npm run build

  docker-frontend:
    needs: [frontend-checks]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Frontend Build Variables
        id: frontend-vars
        run: |

      - name: Build and Push Frontend Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./Frontend
          file: ./Frontend/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ steps.frontend-vars.outputs.FRONT_TAG_MAIN }}
            ${{ steps.frontend-vars.outputs.FRONT_TAG_EXTRA }}

  docker-backend:
    needs: [backend-checks]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Backend Build Variables
        id: backend-vars
        run: |
          # تنظیم متغیرهای بیلد بک‌اند (مشابه کد قبلی)

      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./Backend
          file: ./Backend/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ steps.backend-vars.outputs.BACK_TAG_MAIN }}
            ${{ steps.backend-vars.outputs.BACK_TAG_EXTRA }}
